### ISSUE TITLE
Dodanie menu górnego, stopki i wyszukiwarki od strony frontendu

### ISSUE THREAD

**Issue by pikol93** [pikol93/PG_BE#4]
Wymaganie 3.c.

> c. Sklep posiada menu górne, stopkę, wyszukiwarkę, umożliwia logowanie i rejestrację, prezentuje listę produktów i umożliwia ich wybór oraz zakup, dostępne są strony O sklepie, Formy płatności i inne standardowo oferowane strony, dostępne zaraz po instalacji. Możliwe jest przeprowadzenie procesu rejestracji, logowania oraz dostęp do historii zamówień.

**Comment by Sladamos** [comment]
Blokowane przez #5
